Started by user [8mha:AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzOEgYu/dLi1CL9vNKcHACFIKlWvwAAAA==[0manonymous
Building in workspace /Users/alekh.raj/Documents/creating_plugin/newplugin/work/jobs/dsf/workspace
Exception occured : java.util.concurrent.ExecutionException: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 (runtime)' from ["maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication"] into /Users/alekh.raj/dev/test/DepCheck/logs/repo
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.flipkart.depcheck.engine.Engine.collate(Engine.java:47)
	at com.flipkart.depcheck.engine.Engine.scanAndAnalyze(Engine.java:40)
	at com.flipkart.depcheck.app.App.analyze(App.java:45)
	at com.flipkart.depcheck.app.App.main(App.java:32)
	at ABC.newplugin.HelloWorldBuilder.perform(HelloWorldBuilder.java:78)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 (runtime)' from ["maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication"] into /Users/alekh.raj/dev/test/DepCheck/logs/repo
	at com.jcabi.aether.Aether.fetch(Aether.java:237)
	at com.jcabi.aether.Aether.resolve_aroundBody2(Aether.java:180)
	at com.jcabi.aether.Aether$AjcClosure3.run(Aether.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.aether.Aether.resolve(Aether.java:177)
	at com.jcabi.aether.Aether.resolve_aroundBody0(Aether.java:163)
	at com.jcabi.aether.Aether$AjcClosure1.run(Aether.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.aether.Aether.resolve(Aether.java:156)
	at com.flipkart.depcheck.analyzers.PomAnalyzer.getAllDependencies(PomAnalyzer.java:65)
	at com.flipkart.depcheck.engine.Engine$1.call(Engine.java:61)
	at com.flipkart.depcheck.engine.Engine$1.call(Engine.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: failed to load 'org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 (runtime)' from ["maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication"] into /Users/alekh.raj/dev/test/DepCheck/logs/repo
	... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 in maven-central (http://repo1.maven.org/maven2/)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at com.jcabi.aether.Aether.fetch(Aether.java:228)
	... 21 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 in maven-central (http://repo1.maven.org/maven2/)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 22 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jenkins-ci.lib:cvsclient:jar:71-jenkins-11 in maven-central (http://repo1.maven.org/maven2/)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$3.wrap(AsyncRepositoryConnector.java:1542)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$3.wrap(AsyncRepositoryConnector.java:1537)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$GetTask.flush(AsyncRepositoryConnector.java:1035)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector.get(AsyncRepositoryConnector.java:409)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:457)
	... 24 more

FATAL: Exception occured : 
[8mha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=[0mjava.io.FileNotFoundException: Exception occured : 
	at ABC.newplugin.HelloWorldBuilder.perform(HelloWorldBuilder.java:93)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Finished: FAILURE
